package spill.localisation;

extern class TextFieldFit extends flash.display.MovieClip {
	var antiAliasType : String;
	var bold : Bool;
	var disableWordwrap : Bool;
	var embedFonts : Bool;
	var font : String;
	var glowBlur : Float;
	var glowColor : UInt;
	var glowQuality : Float;
	var glowStrength : Float;
	var gridFitType : String;
	var hAlign : String;
	var italic : Bool;
	var multiline : Bool;
	var selectable : Bool;
	var text : String;
	var textColor : UInt;
	var textSize : Float;
	var underline : Bool;
	var useGlowFilter : Bool;
	var vAlign : String;
	function new() : Void;
	function setSize(_w : Float, _h : Float) : Void;
	private var _antiAliasType : String;
	private var _bold : Bool;
	private var _disableWordwrap : Bool;
	private var _embedFonts : Bool;
	private var _font : String;
	private var _glowBlur : Float;
	private var _glowColor : UInt;
	private var _glowQuality : Float;
	private var _glowStrength : Float;
	private var _gridFitType : String;
	private var _hAlign : String;
	private var _italic : Bool;
	private var _multiline : Bool;
	private var _selectable : Bool;
	private var _text : String;
	private var _textColor : UInt;
	private var _textSize : Float;
	private var _underline : Bool;
	private var _useGlowFilter : Bool;
	private var _vAlign : String;
	private function updateProperties() : Void;
	static var alwaysCheckWidth : Bool;
	static var embedFonts : Bool;
	static var forceAAType : String;
	static var forceFont : String;
}
